server:
  port: 8090

spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/users?connectionTimeZone=UTC
#    username: root
#    password: 1234
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/users?serverTimezone=UTC
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true